CREATE TABLE loans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    loan_type VARCHAR(100) NOT NULL,
    principal_amount NUMERIC(18,2) NOT NULL CHECK (principal_amount > 0),
    interest_rate NUMERIC(5,2) NOT NULL CHECK (interest_rate >= 0),
    term_months INTEGER CHECK (term_months > 0),
    monthly_payment NUMERIC(18,2),
    admin_fee NUMERIC(18,2) NOT NULL DEFAULT 0.00,
    total_interest NUMERIC(18,2),
    total_repayment NUMERIC(18,2),
    total_repaid NUMERIC(18,2) NOT NULL DEFAULT 0.00,
    total_unpaid NUMERIC(18,2) NOT NULL DEFAULT 0.00,
    number_of_repayments INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL CHECK (
        status IN ('pending', 'approved', 'forwarded', 'repaid', 'defaulted', 'rejected')
    ),
    due_date TIMESTAMPTZ,
    approved_date TIMESTAMPTZ,
    next_payment_date TIMESTAMPTZ,
    collateral TEXT NOT NULL,
    borrower_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    guarantor_name VARCHAR(255),
    guarantor_email VARCHAR(255),
    guarantor_phone VARCHAR(100),
    guarantor_ippis_no VARCHAR(100),
    bank_name VARCHAR(255),
    account_number VARCHAR(100),
    account_holder VARCHAR(255),
    bvn VARCHAR(100),
    occupation VARCHAR(255),
    employer_name VARCHAR(255),
    employer_address TEXT,
    employer_phone VARCHAR(100),
    ippis_no VARCHAR(100),
    statement TEXT,
    admin_fee_receipt TEXT,
    collateral_document TEXT,
    loan_interest TEXT,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    loan_type_id UUID NOT NULL REFERENCES loan_types(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);