// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: init.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const approveLoan = `-- name: ApproveLoan :exec
UPDATE loans
SET
    status = 'approved',
    approved_date = NOW()
WHERE id = $1
`

func (q *Queries) ApproveLoan(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, approveLoan, id)
	return err
}

const countDeposits = `-- name: CountDeposits :one
SELECT COUNT(*) AS total
FROM deposits
`

func (q *Queries) CountDeposits(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeposits)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countDepositsByUserID = `-- name: CountDepositsByUserID :one
SELECT COUNT(*)
FROM deposits
WHERE user_id = $1
`

func (q *Queries) CountDepositsByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDepositsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLoans = `-- name: CountLoans :one
SELECT COUNT(*) AS total
FROM loans
`

func (q *Queries) CountLoans(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLoans)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countLoansByUserID = `-- name: CountLoansByUserID :one
SELECT COUNT(*)
FROM loans
WHERE user_id = $1
`

func (q *Queries) CountLoansByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLoansByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingLoans = `-- name: CountPendingLoans :one
SELECT COUNT(*) AS total
FROM loans
WHERE status = 'pending'
`

func (q *Queries) CountPendingLoans(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingLoans)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countStaffs = `-- name: CountStaffs :one
SELECT COUNT(*) AS total
FROM staffs
`

func (q *Queries) CountStaffs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countStaffs)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) AS total
FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createDeposit = `-- name: CreateDeposit :one
INSERT INTO deposits (
    tx_id,
    status,
    type,
    months,
    amount,
    receipt,
    loan_id,
    user_id,
    email
)
VALUES (
    $1,$2,$3,$4,$5,$6,$7,$8,$9
)
RETURNING id, tx_id, status, type, months, amount, receipt, loan_id, user_id, email, created_at, updated_at
`

type CreateDepositParams struct {
	TxID    uuid.UUID `db:"tx_id" json:"tx_id"`
	Status  string    `db:"status" json:"status"`
	Type    string    `db:"type" json:"type"`
	Months  int32     `db:"months" json:"months"`
	Amount  string    `db:"amount" json:"amount"`
	Receipt string    `db:"receipt" json:"receipt"`
	LoanID  uuid.UUID `db:"loan_id" json:"loan_id"`
	UserID  uuid.UUID `db:"user_id" json:"user_id"`
	Email   string    `db:"email" json:"email"`
}

func (q *Queries) CreateDeposit(ctx context.Context, arg CreateDepositParams) (Deposit, error) {
	row := q.db.QueryRowContext(ctx, createDeposit,
		arg.TxID,
		arg.Status,
		arg.Type,
		arg.Months,
		arg.Amount,
		arg.Receipt,
		arg.LoanID,
		arg.UserID,
		arg.Email,
	)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.TxID,
		&i.Status,
		&i.Type,
		&i.Months,
		&i.Amount,
		&i.Receipt,
		&i.LoanID,
		&i.UserID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLoan = `-- name: CreateLoan :one
INSERT INTO loans (
    loan_type,
    principal_amount,
    interest_rate,
    term_months,
    monthly_payment,
    admin_fee,
    total_interest,
    total_repayment,
    total_repaid,
    total_unpaid,
    number_of_repayments,
    status,
    due_date,
    approved_date,
    next_payment_date,
    collateral,
    borrower_name,
    email,
    guarantor_name,
    guarantor_email,
    guarantor_phone,
    guarantor_ippis_no,
    bank_name,
    account_number,
    account_holder,
    bvn,
    occupation,
    employer_name,
    employer_address,
    employer_phone,
    ippis_no,
    statement,
    admin_fee_receipt,
    collateral_document,
    loan_interest,
    user_id,
    loan_type_id
)
VALUES (
    $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,
    $11,$12,$13,$14,$15,$16,$17,$18,$19,$20,
    $21,$22,$23,$24,$25,$26,$27,$28,$29,$30,
    $31,$32,$33,$34,$35,$36,$37
)
RETURNING id, loan_type, principal_amount, interest_rate, term_months, monthly_payment, admin_fee, total_interest, total_repayment, total_repaid, total_unpaid, number_of_repayments, status, due_date, approved_date, next_payment_date, collateral, borrower_name, email, guarantor_name, guarantor_email, guarantor_phone, guarantor_ippis_no, bank_name, account_number, account_holder, bvn, occupation, employer_name, employer_address, employer_phone, ippis_no, statement, admin_fee_receipt, collateral_document, loan_interest, user_id, loan_type_id, created_at, updated_at
`

type CreateLoanParams struct {
	LoanType           string         `db:"loan_type" json:"loan_type"`
	PrincipalAmount    string         `db:"principal_amount" json:"principal_amount"`
	InterestRate       string         `db:"interest_rate" json:"interest_rate"`
	TermMonths         sql.NullInt32  `db:"term_months" json:"term_months"`
	MonthlyPayment     sql.NullString `db:"monthly_payment" json:"monthly_payment"`
	AdminFee           string         `db:"admin_fee" json:"admin_fee"`
	TotalInterest      sql.NullString `db:"total_interest" json:"total_interest"`
	TotalRepayment     sql.NullString `db:"total_repayment" json:"total_repayment"`
	TotalRepaid        string         `db:"total_repaid" json:"total_repaid"`
	TotalUnpaid        string         `db:"total_unpaid" json:"total_unpaid"`
	NumberOfRepayments int32          `db:"number_of_repayments" json:"number_of_repayments"`
	Status             string         `db:"status" json:"status"`
	DueDate            sql.NullTime   `db:"due_date" json:"due_date"`
	ApprovedDate       sql.NullTime   `db:"approved_date" json:"approved_date"`
	NextPaymentDate    sql.NullTime   `db:"next_payment_date" json:"next_payment_date"`
	Collateral         string         `db:"collateral" json:"collateral"`
	BorrowerName       string         `db:"borrower_name" json:"borrower_name"`
	Email              string         `db:"email" json:"email"`
	GuarantorName      sql.NullString `db:"guarantor_name" json:"guarantor_name"`
	GuarantorEmail     sql.NullString `db:"guarantor_email" json:"guarantor_email"`
	GuarantorPhone     sql.NullString `db:"guarantor_phone" json:"guarantor_phone"`
	GuarantorIppisNo   sql.NullString `db:"guarantor_ippis_no" json:"guarantor_ippis_no"`
	BankName           sql.NullString `db:"bank_name" json:"bank_name"`
	AccountNumber      sql.NullString `db:"account_number" json:"account_number"`
	AccountHolder      sql.NullString `db:"account_holder" json:"account_holder"`
	Bvn                sql.NullString `db:"bvn" json:"bvn"`
	Occupation         sql.NullString `db:"occupation" json:"occupation"`
	EmployerName       sql.NullString `db:"employer_name" json:"employer_name"`
	EmployerAddress    sql.NullString `db:"employer_address" json:"employer_address"`
	EmployerPhone      sql.NullString `db:"employer_phone" json:"employer_phone"`
	IppisNo            sql.NullString `db:"ippis_no" json:"ippis_no"`
	Statement          sql.NullString `db:"statement" json:"statement"`
	AdminFeeReceipt    sql.NullString `db:"admin_fee_receipt" json:"admin_fee_receipt"`
	CollateralDocument sql.NullString `db:"collateral_document" json:"collateral_document"`
	LoanInterest       sql.NullString `db:"loan_interest" json:"loan_interest"`
	UserID             uuid.UUID      `db:"user_id" json:"user_id"`
	LoanTypeID         uuid.UUID      `db:"loan_type_id" json:"loan_type_id"`
}

func (q *Queries) CreateLoan(ctx context.Context, arg CreateLoanParams) (Loan, error) {
	row := q.db.QueryRowContext(ctx, createLoan,
		arg.LoanType,
		arg.PrincipalAmount,
		arg.InterestRate,
		arg.TermMonths,
		arg.MonthlyPayment,
		arg.AdminFee,
		arg.TotalInterest,
		arg.TotalRepayment,
		arg.TotalRepaid,
		arg.TotalUnpaid,
		arg.NumberOfRepayments,
		arg.Status,
		arg.DueDate,
		arg.ApprovedDate,
		arg.NextPaymentDate,
		arg.Collateral,
		arg.BorrowerName,
		arg.Email,
		arg.GuarantorName,
		arg.GuarantorEmail,
		arg.GuarantorPhone,
		arg.GuarantorIppisNo,
		arg.BankName,
		arg.AccountNumber,
		arg.AccountHolder,
		arg.Bvn,
		arg.Occupation,
		arg.EmployerName,
		arg.EmployerAddress,
		arg.EmployerPhone,
		arg.IppisNo,
		arg.Statement,
		arg.AdminFeeReceipt,
		arg.CollateralDocument,
		arg.LoanInterest,
		arg.UserID,
		arg.LoanTypeID,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.LoanType,
		&i.PrincipalAmount,
		&i.InterestRate,
		&i.TermMonths,
		&i.MonthlyPayment,
		&i.AdminFee,
		&i.TotalInterest,
		&i.TotalRepayment,
		&i.TotalRepaid,
		&i.TotalUnpaid,
		&i.NumberOfRepayments,
		&i.Status,
		&i.DueDate,
		&i.ApprovedDate,
		&i.NextPaymentDate,
		&i.Collateral,
		&i.BorrowerName,
		&i.Email,
		&i.GuarantorName,
		&i.GuarantorEmail,
		&i.GuarantorPhone,
		&i.GuarantorIppisNo,
		&i.BankName,
		&i.AccountNumber,
		&i.AccountHolder,
		&i.Bvn,
		&i.Occupation,
		&i.EmployerName,
		&i.EmployerAddress,
		&i.EmployerPhone,
		&i.IppisNo,
		&i.Statement,
		&i.AdminFeeReceipt,
		&i.CollateralDocument,
		&i.LoanInterest,
		&i.UserID,
		&i.LoanTypeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLoanType = `-- name: CreateLoanType :one
INSERT INTO loan_types (name, rate)
VALUES ($1, $2)
RETURNING id, name, rate, created_at, updated_at
`

type CreateLoanTypeParams struct {
	Name string `db:"name" json:"name"`
	Rate string `db:"rate" json:"rate"`
}

func (q *Queries) CreateLoanType(ctx context.Context, arg CreateLoanTypeParams) (LoanType, error) {
	row := q.db.QueryRowContext(ctx, createLoanType, arg.Name, arg.Rate)
	var i LoanType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStaff = `-- name: CreateStaff :one
INSERT INTO staffs (email, password_hash, full_name, role)
VALUES ($1, $2, $3, $4)
RETURNING id, email, full_name, role, created_at
`

type CreateStaffParams struct {
	Email        string       `db:"email" json:"email"`
	PasswordHash string       `db:"password_hash" json:"password_hash"`
	FullName     string       `db:"full_name" json:"full_name"`
	Role         NullUserRole `db:"role" json:"role"`
}

type CreateStaffRow struct {
	ID        uuid.UUID    `db:"id" json:"id"`
	Email     string       `db:"email" json:"email"`
	FullName  string       `db:"full_name" json:"full_name"`
	Role      NullUserRole `db:"role" json:"role"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateStaff(ctx context.Context, arg CreateStaffParams) (CreateStaffRow, error) {
	row := q.db.QueryRowContext(ctx, createStaff,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.Role,
	)
	var i CreateStaffRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    password,
    first_name,
    last_name,
    address,
    lga,
    zip_code,
    state,
    gender,
    marital_status,
    phone1,
    phone2,
    occupation,
    about_us,
    verification_code,
    terms_accepted,
    verification_code_expires_at
)
VALUES (
    $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,
    $11,$12,$13,$14,$15,$16,$17
)
RETURNING id, email, password, email_verified, role, verification_code, verification_code_expires_at, account_enabled, last_login, first_name, last_name, address, lga, zip_code, about_us, state, gender, marital_status, phone1, phone2, occupation, terms_accepted, img_url, created_at, updated_at
`

type CreateUserParams struct {
	Email                     string         `db:"email" json:"email"`
	Password                  string         `db:"password" json:"password"`
	FirstName                 string         `db:"first_name" json:"first_name"`
	LastName                  string         `db:"last_name" json:"last_name"`
	Address                   string         `db:"address" json:"address"`
	Lga                       string         `db:"lga" json:"lga"`
	ZipCode                   string         `db:"zip_code" json:"zip_code"`
	State                     string         `db:"state" json:"state"`
	Gender                    string         `db:"gender" json:"gender"`
	MaritalStatus             string         `db:"marital_status" json:"marital_status"`
	Phone1                    string         `db:"phone1" json:"phone1"`
	Phone2                    string         `db:"phone2" json:"phone2"`
	Occupation                string         `db:"occupation" json:"occupation"`
	AboutUs                   string         `db:"about_us" json:"about_us"`
	VerificationCode          sql.NullString `db:"verification_code" json:"verification_code"`
	TermsAccepted             bool           `db:"terms_accepted" json:"terms_accepted"`
	VerificationCodeExpiresAt sql.NullTime   `db:"verification_code_expires_at" json:"verification_code_expires_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.Password,
		arg.FirstName,
		arg.LastName,
		arg.Address,
		arg.Lga,
		arg.ZipCode,
		arg.State,
		arg.Gender,
		arg.MaritalStatus,
		arg.Phone1,
		arg.Phone2,
		arg.Occupation,
		arg.AboutUs,
		arg.VerificationCode,
		arg.TermsAccepted,
		arg.VerificationCodeExpiresAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.EmailVerified,
		&i.Role,
		&i.VerificationCode,
		&i.VerificationCodeExpiresAt,
		&i.AccountEnabled,
		&i.LastLogin,
		&i.FirstName,
		&i.LastName,
		&i.Address,
		&i.Lga,
		&i.ZipCode,
		&i.AboutUs,
		&i.State,
		&i.Gender,
		&i.MaritalStatus,
		&i.Phone1,
		&i.Phone2,
		&i.Occupation,
		&i.TermsAccepted,
		&i.ImgUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const dashboardStats = `-- name: DashboardStats :one
SELECT
    (SELECT COUNT(*) FROM loans) AS loans,
    (SELECT COUNT(*) FROM deposits) AS deposits,
    (SELECT COUNT(*) FROM users) AS users
`

type DashboardStatsRow struct {
	Loans    int64 `db:"loans" json:"loans"`
	Deposits int64 `db:"deposits" json:"deposits"`
	Users    int64 `db:"users" json:"users"`
}

func (q *Queries) DashboardStats(ctx context.Context) (DashboardStatsRow, error) {
	row := q.db.QueryRowContext(ctx, dashboardStats)
	var i DashboardStatsRow
	err := row.Scan(&i.Loans, &i.Deposits, &i.Users)
	return i, err
}

const deleteLoanType = `-- name: DeleteLoanType :exec
DELETE FROM loan_types
WHERE id = $1
`

func (q *Queries) DeleteLoanType(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLoanType, id)
	return err
}

const deleteStaff = `-- name: DeleteStaff :exec
DELETE FROM staffs WHERE id = $1
`

func (q *Queries) DeleteStaff(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteStaff, id)
	return err
}

const getAllStaff = `-- name: GetAllStaff :many
SELECT id, email, full_name, role, account_enabled, last_login_at, created_at
FROM staffs
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type GetAllStaffParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type GetAllStaffRow struct {
	ID             uuid.UUID    `db:"id" json:"id"`
	Email          string       `db:"email" json:"email"`
	FullName       string       `db:"full_name" json:"full_name"`
	Role           NullUserRole `db:"role" json:"role"`
	AccountEnabled sql.NullBool `db:"account_enabled" json:"account_enabled"`
	LastLoginAt    sql.NullTime `db:"last_login_at" json:"last_login_at"`
	CreatedAt      sql.NullTime `db:"created_at" json:"created_at"`
}

func (q *Queries) GetAllStaff(ctx context.Context, arg GetAllStaffParams) ([]GetAllStaffRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllStaff, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllStaffRow{}
	for rows.Next() {
		var i GetAllStaffRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Role,
			&i.AccountEnabled,
			&i.LastLoginAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDepositByID = `-- name: GetDepositByID :one
SELECT id, tx_id, status, type, months, amount, receipt, loan_id, user_id, email, created_at, updated_at
FROM deposits
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetDepositByID(ctx context.Context, id uuid.UUID) (Deposit, error) {
	row := q.db.QueryRowContext(ctx, getDepositByID, id)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.TxID,
		&i.Status,
		&i.Type,
		&i.Months,
		&i.Amount,
		&i.Receipt,
		&i.LoanID,
		&i.UserID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeposits = `-- name: GetDeposits :many
SELECT id, tx_id, status, type, months, amount, receipt, loan_id, user_id, email, created_at, updated_at
FROM deposits
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type GetDepositsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) GetDeposits(ctx context.Context, arg GetDepositsParams) ([]Deposit, error) {
	rows, err := q.db.QueryContext(ctx, getDeposits, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deposit{}
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.TxID,
			&i.Status,
			&i.Type,
			&i.Months,
			&i.Amount,
			&i.Receipt,
			&i.LoanID,
			&i.UserID,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDepositsByUserID = `-- name: GetDepositsByUserID :many
SELECT id, tx_id, status, type, months, amount, receipt, loan_id, user_id, email, created_at, updated_at
FROM deposits
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type GetDepositsByUserIDParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

func (q *Queries) GetDepositsByUserID(ctx context.Context, arg GetDepositsByUserIDParams) ([]Deposit, error) {
	rows, err := q.db.QueryContext(ctx, getDepositsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deposit{}
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.TxID,
			&i.Status,
			&i.Type,
			&i.Months,
			&i.Amount,
			&i.Receipt,
			&i.LoanID,
			&i.UserID,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLoanByID = `-- name: GetLoanByID :one
SELECT id, loan_type, principal_amount, interest_rate, term_months, monthly_payment, admin_fee, total_interest, total_repayment, total_repaid, total_unpaid, number_of_repayments, status, due_date, approved_date, next_payment_date, collateral, borrower_name, email, guarantor_name, guarantor_email, guarantor_phone, guarantor_ippis_no, bank_name, account_number, account_holder, bvn, occupation, employer_name, employer_address, employer_phone, ippis_no, statement, admin_fee_receipt, collateral_document, loan_interest, user_id, loan_type_id, created_at, updated_at
FROM loans
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetLoanByID(ctx context.Context, id uuid.UUID) (Loan, error) {
	row := q.db.QueryRowContext(ctx, getLoanByID, id)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.LoanType,
		&i.PrincipalAmount,
		&i.InterestRate,
		&i.TermMonths,
		&i.MonthlyPayment,
		&i.AdminFee,
		&i.TotalInterest,
		&i.TotalRepayment,
		&i.TotalRepaid,
		&i.TotalUnpaid,
		&i.NumberOfRepayments,
		&i.Status,
		&i.DueDate,
		&i.ApprovedDate,
		&i.NextPaymentDate,
		&i.Collateral,
		&i.BorrowerName,
		&i.Email,
		&i.GuarantorName,
		&i.GuarantorEmail,
		&i.GuarantorPhone,
		&i.GuarantorIppisNo,
		&i.BankName,
		&i.AccountNumber,
		&i.AccountHolder,
		&i.Bvn,
		&i.Occupation,
		&i.EmployerName,
		&i.EmployerAddress,
		&i.EmployerPhone,
		&i.IppisNo,
		&i.Statement,
		&i.AdminFeeReceipt,
		&i.CollateralDocument,
		&i.LoanInterest,
		&i.UserID,
		&i.LoanTypeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLoanTypeByID = `-- name: GetLoanTypeByID :one
SELECT id, name, rate, created_at, updated_at 
FROM loan_types
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetLoanTypeByID(ctx context.Context, id uuid.UUID) (LoanType, error) {
	row := q.db.QueryRowContext(ctx, getLoanTypeByID, id)
	var i LoanType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLoanTypeByName = `-- name: GetLoanTypeByName :one
SELECT id, name, rate, created_at, updated_at FROM loan_types
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetLoanTypeByName(ctx context.Context, id uuid.UUID) (LoanType, error) {
	row := q.db.QueryRowContext(ctx, getLoanTypeByName, id)
	var i LoanType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLoans = `-- name: GetLoans :many
SELECT id, loan_type, principal_amount, interest_rate, term_months, monthly_payment, admin_fee, total_interest, total_repayment, total_repaid, total_unpaid, number_of_repayments, status, due_date, approved_date, next_payment_date, collateral, borrower_name, email, guarantor_name, guarantor_email, guarantor_phone, guarantor_ippis_no, bank_name, account_number, account_holder, bvn, occupation, employer_name, employer_address, employer_phone, ippis_no, statement, admin_fee_receipt, collateral_document, loan_interest, user_id, loan_type_id, created_at, updated_at
FROM loans
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type GetLoansParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) GetLoans(ctx context.Context, arg GetLoansParams) ([]Loan, error) {
	rows, err := q.db.QueryContext(ctx, getLoans, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Loan{}
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.LoanType,
			&i.PrincipalAmount,
			&i.InterestRate,
			&i.TermMonths,
			&i.MonthlyPayment,
			&i.AdminFee,
			&i.TotalInterest,
			&i.TotalRepayment,
			&i.TotalRepaid,
			&i.TotalUnpaid,
			&i.NumberOfRepayments,
			&i.Status,
			&i.DueDate,
			&i.ApprovedDate,
			&i.NextPaymentDate,
			&i.Collateral,
			&i.BorrowerName,
			&i.Email,
			&i.GuarantorName,
			&i.GuarantorEmail,
			&i.GuarantorPhone,
			&i.GuarantorIppisNo,
			&i.BankName,
			&i.AccountNumber,
			&i.AccountHolder,
			&i.Bvn,
			&i.Occupation,
			&i.EmployerName,
			&i.EmployerAddress,
			&i.EmployerPhone,
			&i.IppisNo,
			&i.Statement,
			&i.AdminFeeReceipt,
			&i.CollateralDocument,
			&i.LoanInterest,
			&i.UserID,
			&i.LoanTypeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLoansByUserID = `-- name: GetLoansByUserID :many
SELECT id, loan_type, principal_amount, interest_rate, term_months, monthly_payment, admin_fee, total_interest, total_repayment, total_repaid, total_unpaid, number_of_repayments, status, due_date, approved_date, next_payment_date, collateral, borrower_name, email, guarantor_name, guarantor_email, guarantor_phone, guarantor_ippis_no, bank_name, account_number, account_holder, bvn, occupation, employer_name, employer_address, employer_phone, ippis_no, statement, admin_fee_receipt, collateral_document, loan_interest, user_id, loan_type_id, created_at, updated_at
FROM loans
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type GetLoansByUserIDParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

func (q *Queries) GetLoansByUserID(ctx context.Context, arg GetLoansByUserIDParams) ([]Loan, error) {
	rows, err := q.db.QueryContext(ctx, getLoansByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Loan{}
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.LoanType,
			&i.PrincipalAmount,
			&i.InterestRate,
			&i.TermMonths,
			&i.MonthlyPayment,
			&i.AdminFee,
			&i.TotalInterest,
			&i.TotalRepayment,
			&i.TotalRepaid,
			&i.TotalUnpaid,
			&i.NumberOfRepayments,
			&i.Status,
			&i.DueDate,
			&i.ApprovedDate,
			&i.NextPaymentDate,
			&i.Collateral,
			&i.BorrowerName,
			&i.Email,
			&i.GuarantorName,
			&i.GuarantorEmail,
			&i.GuarantorPhone,
			&i.GuarantorIppisNo,
			&i.BankName,
			&i.AccountNumber,
			&i.AccountHolder,
			&i.Bvn,
			&i.Occupation,
			&i.EmployerName,
			&i.EmployerAddress,
			&i.EmployerPhone,
			&i.IppisNo,
			&i.Statement,
			&i.AdminFeeReceipt,
			&i.CollateralDocument,
			&i.LoanInterest,
			&i.UserID,
			&i.LoanTypeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaffByEmail = `-- name: GetStaffByEmail :one
SELECT id, email, password_hash, full_name, role, account_enabled, last_login_at, created_at, updated_at
FROM staffs
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetStaffByEmail(ctx context.Context, email string) (Staff, error) {
	row := q.db.QueryRowContext(ctx, getStaffByEmail, email)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.AccountEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaffByID = `-- name: GetStaffByID :one
SELECT id, email, full_name, role, account_enabled, created_at
FROM staffs
WHERE id = $1 LIMIT 1
`

type GetStaffByIDRow struct {
	ID             uuid.UUID    `db:"id" json:"id"`
	Email          string       `db:"email" json:"email"`
	FullName       string       `db:"full_name" json:"full_name"`
	Role           NullUserRole `db:"role" json:"role"`
	AccountEnabled sql.NullBool `db:"account_enabled" json:"account_enabled"`
	CreatedAt      sql.NullTime `db:"created_at" json:"created_at"`
}

func (q *Queries) GetStaffByID(ctx context.Context, id uuid.UUID) (GetStaffByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getStaffByID, id)
	var i GetStaffByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.AccountEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const getStaffWithPassword = `-- name: GetStaffWithPassword :one
SELECT id, email, full_name, password_hash, role, account_enabled, created_at
FROM staffs
WHERE id = $1 LIMIT 1
`

type GetStaffWithPasswordRow struct {
	ID             uuid.UUID    `db:"id" json:"id"`
	Email          string       `db:"email" json:"email"`
	FullName       string       `db:"full_name" json:"full_name"`
	PasswordHash   string       `db:"password_hash" json:"password_hash"`
	Role           NullUserRole `db:"role" json:"role"`
	AccountEnabled sql.NullBool `db:"account_enabled" json:"account_enabled"`
	CreatedAt      sql.NullTime `db:"created_at" json:"created_at"`
}

func (q *Queries) GetStaffWithPassword(ctx context.Context, id uuid.UUID) (GetStaffWithPasswordRow, error) {
	row := q.db.QueryRowContext(ctx, getStaffWithPassword, id)
	var i GetStaffWithPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.Role,
		&i.AccountEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, email_verified, role, verification_code, verification_code_expires_at, account_enabled, last_login, first_name, last_name, address, lga, zip_code, about_us, state, gender, marital_status, phone1, phone2, occupation, terms_accepted, img_url, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.EmailVerified,
		&i.Role,
		&i.VerificationCode,
		&i.VerificationCodeExpiresAt,
		&i.AccountEnabled,
		&i.LastLogin,
		&i.FirstName,
		&i.LastName,
		&i.Address,
		&i.Lga,
		&i.ZipCode,
		&i.AboutUs,
		&i.State,
		&i.Gender,
		&i.MaritalStatus,
		&i.Phone1,
		&i.Phone2,
		&i.Occupation,
		&i.TermsAccepted,
		&i.ImgUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    email,
    email_verified,
    role,
    account_enabled,
    last_login,
    first_name,
    last_name,
    address,
    lga,
    zip_code,
    state,
    gender,
    marital_status,
    phone1,
    phone2,
    occupation,
    password,
    img_url,
    about_us,
    created_at,
    terms_accepted,
    updated_at
FROM users
WHERE id = $1
LIMIT 1
`

type GetUserByIDRow struct {
	ID             uuid.UUID `db:"id" json:"id"`
	Email          string    `db:"email" json:"email"`
	EmailVerified  bool      `db:"email_verified" json:"email_verified"`
	Role           UserRole  `db:"role" json:"role"`
	AccountEnabled bool      `db:"account_enabled" json:"account_enabled"`
	LastLogin      time.Time `db:"last_login" json:"last_login"`
	FirstName      string    `db:"first_name" json:"first_name"`
	LastName       string    `db:"last_name" json:"last_name"`
	Address        string    `db:"address" json:"address"`
	Lga            string    `db:"lga" json:"lga"`
	ZipCode        string    `db:"zip_code" json:"zip_code"`
	State          string    `db:"state" json:"state"`
	Gender         string    `db:"gender" json:"gender"`
	MaritalStatus  string    `db:"marital_status" json:"marital_status"`
	Phone1         string    `db:"phone1" json:"phone1"`
	Phone2         string    `db:"phone2" json:"phone2"`
	Occupation     string    `db:"occupation" json:"occupation"`
	Password       string    `db:"password" json:"password"`
	ImgUrl         string    `db:"img_url" json:"img_url"`
	AboutUs        string    `db:"about_us" json:"about_us"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	TermsAccepted  bool      `db:"terms_accepted" json:"terms_accepted"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Role,
		&i.AccountEnabled,
		&i.LastLogin,
		&i.FirstName,
		&i.LastName,
		&i.Address,
		&i.Lga,
		&i.ZipCode,
		&i.State,
		&i.Gender,
		&i.MaritalStatus,
		&i.Phone1,
		&i.Phone2,
		&i.Occupation,
		&i.Password,
		&i.ImgUrl,
		&i.AboutUs,
		&i.CreatedAt,
		&i.TermsAccepted,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserForLogin = `-- name: GetUserForLogin :one
SELECT
    id,
    email,
    password,
    email_verified,
    account_enabled,
    role
FROM users
WHERE email = $1
LIMIT 1
`

type GetUserForLoginRow struct {
	ID             uuid.UUID `db:"id" json:"id"`
	Email          string    `db:"email" json:"email"`
	Password       string    `db:"password" json:"password"`
	EmailVerified  bool      `db:"email_verified" json:"email_verified"`
	AccountEnabled bool      `db:"account_enabled" json:"account_enabled"`
	Role           UserRole  `db:"role" json:"role"`
}

func (q *Queries) GetUserForLogin(ctx context.Context, email string) (GetUserForLoginRow, error) {
	row := q.db.QueryRowContext(ctx, getUserForLogin, email)
	var i GetUserForLoginRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.EmailVerified,
		&i.AccountEnabled,
		&i.Role,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT 
    id, 
    email, 
    email_verified, 
    role, 
    account_enabled, 
    last_login, 
    first_name, 
    last_name, 
    address, 
    lga, 
    zip_code, 
    state, 
    gender, 
    marital_status, 
    phone1, 
    phone2, 
    occupation, 
    img_url, 
    about_us,
    terms_accepted,
    created_at, 
    updated_at 
FROM users ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type GetUsersParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type GetUsersRow struct {
	ID             uuid.UUID `db:"id" json:"id"`
	Email          string    `db:"email" json:"email"`
	EmailVerified  bool      `db:"email_verified" json:"email_verified"`
	Role           UserRole  `db:"role" json:"role"`
	AccountEnabled bool      `db:"account_enabled" json:"account_enabled"`
	LastLogin      time.Time `db:"last_login" json:"last_login"`
	FirstName      string    `db:"first_name" json:"first_name"`
	LastName       string    `db:"last_name" json:"last_name"`
	Address        string    `db:"address" json:"address"`
	Lga            string    `db:"lga" json:"lga"`
	ZipCode        string    `db:"zip_code" json:"zip_code"`
	State          string    `db:"state" json:"state"`
	Gender         string    `db:"gender" json:"gender"`
	MaritalStatus  string    `db:"marital_status" json:"marital_status"`
	Phone1         string    `db:"phone1" json:"phone1"`
	Phone2         string    `db:"phone2" json:"phone2"`
	Occupation     string    `db:"occupation" json:"occupation"`
	ImgUrl         string    `db:"img_url" json:"img_url"`
	AboutUs        string    `db:"about_us" json:"about_us"`
	TermsAccepted  bool      `db:"terms_accepted" json:"terms_accepted"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) ([]GetUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersRow{}
	for rows.Next() {
		var i GetUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.EmailVerified,
			&i.Role,
			&i.AccountEnabled,
			&i.LastLogin,
			&i.FirstName,
			&i.LastName,
			&i.Address,
			&i.Lga,
			&i.ZipCode,
			&i.State,
			&i.Gender,
			&i.MaritalStatus,
			&i.Phone1,
			&i.Phone2,
			&i.Occupation,
			&i.ImgUrl,
			&i.AboutUs,
			&i.TermsAccepted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoanTypes = `-- name: ListLoanTypes :many
SELECT id, name, rate, created_at, updated_at 
FROM loan_types
ORDER BY id DESC
`

func (q *Queries) ListLoanTypes(ctx context.Context) ([]LoanType, error) {
	rows, err := q.db.QueryContext(ctx, listLoanTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoanType{}
	for rows.Next() {
		var i LoanType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users
SET last_login = NOW()
WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateLastLogin, id)
	return err
}

const updateLastLoginStaff = `-- name: UpdateLastLoginStaff :exec
UPDATE staffs
SET last_login = NOW()
WHERE id = $1
`

func (q *Queries) UpdateLastLoginStaff(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateLastLoginStaff, id)
	return err
}

const updateLoanRepayment = `-- name: UpdateLoanRepayment :exec
UPDATE loans
SET
    total_repaid = $2,
    total_unpaid = $3,
    number_of_repayments = $4,
    next_payment_date = $5
WHERE id = $1
`

type UpdateLoanRepaymentParams struct {
	ID                 uuid.UUID    `db:"id" json:"id"`
	TotalRepaid        string       `db:"total_repaid" json:"total_repaid"`
	TotalUnpaid        string       `db:"total_unpaid" json:"total_unpaid"`
	NumberOfRepayments int32        `db:"number_of_repayments" json:"number_of_repayments"`
	NextPaymentDate    sql.NullTime `db:"next_payment_date" json:"next_payment_date"`
}

func (q *Queries) UpdateLoanRepayment(ctx context.Context, arg UpdateLoanRepaymentParams) error {
	_, err := q.db.ExecContext(ctx, updateLoanRepayment,
		arg.ID,
		arg.TotalRepaid,
		arg.TotalUnpaid,
		arg.NumberOfRepayments,
		arg.NextPaymentDate,
	)
	return err
}

const updateLoanStatus = `-- name: UpdateLoanStatus :exec
UPDATE loans
SET
    status = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateLoanStatusParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	Status string    `db:"status" json:"status"`
}

func (q *Queries) UpdateLoanStatus(ctx context.Context, arg UpdateLoanStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateLoanStatus, arg.ID, arg.Status)
	return err
}

const updateLoanType = `-- name: UpdateLoanType :exec
UPDATE loan_types
SET name = COALESCE($2, name),
    rate = COALESCE($3, rate)
WHERE id = $1
`

type UpdateLoanTypeParams struct {
	ID   uuid.UUID      `db:"id" json:"id"`
	Name sql.NullString `db:"name" json:"name"`
	Rate sql.NullString `db:"rate" json:"rate"`
}

func (q *Queries) UpdateLoanType(ctx context.Context, arg UpdateLoanTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateLoanType, arg.ID, arg.Name, arg.Rate)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password = $2
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	Password string    `db:"password" json:"password"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.ID, arg.Password)
	return err
}

const updateStaff = `-- name: UpdateStaff :exec
UPDATE staffs
SET
    full_name = COALESCE($2, full_name),
    role = COALESCE($3, role),
    account_enabled = COALESCE($4, account_enabled),
    updated_at = NOW()
WHERE id = $1
`

type UpdateStaffParams struct {
	ID             uuid.UUID      `db:"id" json:"id"`
	FullName       sql.NullString `db:"full_name" json:"full_name"`
	Role           NullUserRole   `db:"role" json:"role"`
	AccountEnabled sql.NullBool   `db:"account_enabled" json:"account_enabled"`
}

func (q *Queries) UpdateStaff(ctx context.Context, arg UpdateStaffParams) error {
	_, err := q.db.ExecContext(ctx, updateStaff,
		arg.ID,
		arg.FullName,
		arg.Role,
		arg.AccountEnabled,
	)
	return err
}

const updateStaffPassword = `-- name: UpdateStaffPassword :exec
UPDATE staffs
SET password_hash = $2
WHERE id = $1
`

type UpdateStaffPasswordParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	PasswordHash string    `db:"password_hash" json:"password_hash"`
}

func (q *Queries) UpdateStaffPassword(ctx context.Context, arg UpdateStaffPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateStaffPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    first_name = COALESCE($1, first_name),
    last_name = COALESCE($2, last_name),
    address = COALESCE($3, address),
    lga = COALESCE($4, lga),
    zip_code = COALESCE($5, zip_code),
    state = COALESCE($6, state),
    gender = COALESCE($7, gender),
    marital_status = COALESCE($8, marital_status),
    phone1 = COALESCE($9, phone1),
    phone2 = COALESCE($10, phone2),
    occupation = COALESCE($11, occupation),
    img_url = COALESCE($12, img_url),
    verification_code = COALESCE($13, verification_code),
    verification_code_expires_at = COALESCE($14, verification_code_expires_at),
    updated_at = NOW()
WHERE id = $15
RETURNING id, email, password, email_verified, role, verification_code, verification_code_expires_at, account_enabled, last_login, first_name, last_name, address, lga, zip_code, about_us, state, gender, marital_status, phone1, phone2, occupation, terms_accepted, img_url, created_at, updated_at
`

type UpdateUserParams struct {
	FirstName                 sql.NullString `db:"first_name" json:"first_name"`
	LastName                  sql.NullString `db:"last_name" json:"last_name"`
	Address                   sql.NullString `db:"address" json:"address"`
	Lga                       sql.NullString `db:"lga" json:"lga"`
	ZipCode                   sql.NullString `db:"zip_code" json:"zip_code"`
	State                     sql.NullString `db:"state" json:"state"`
	Gender                    sql.NullString `db:"gender" json:"gender"`
	MaritalStatus             sql.NullString `db:"marital_status" json:"marital_status"`
	Phone1                    sql.NullString `db:"phone1" json:"phone1"`
	Phone2                    sql.NullString `db:"phone2" json:"phone2"`
	Occupation                sql.NullString `db:"occupation" json:"occupation"`
	ImgUrl                    sql.NullString `db:"img_url" json:"img_url"`
	VerificationCode          sql.NullString `db:"verification_code" json:"verification_code"`
	VerificationCodeExpiresAt sql.NullTime   `db:"verification_code_expires_at" json:"verification_code_expires_at"`
	ID                        uuid.UUID      `db:"id" json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Address,
		arg.Lga,
		arg.ZipCode,
		arg.State,
		arg.Gender,
		arg.MaritalStatus,
		arg.Phone1,
		arg.Phone2,
		arg.Occupation,
		arg.ImgUrl,
		arg.VerificationCode,
		arg.VerificationCodeExpiresAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.EmailVerified,
		&i.Role,
		&i.VerificationCode,
		&i.VerificationCodeExpiresAt,
		&i.AccountEnabled,
		&i.LastLogin,
		&i.FirstName,
		&i.LastName,
		&i.Address,
		&i.Lga,
		&i.ZipCode,
		&i.AboutUs,
		&i.State,
		&i.Gender,
		&i.MaritalStatus,
		&i.Phone1,
		&i.Phone2,
		&i.Occupation,
		&i.TermsAccepted,
		&i.ImgUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    first_name = COALESCE($2, first_name),
    last_name = COALESCE($3, last_name),
    address = COALESCE($4, address),
    lga = COALESCE($5, lga),
    zip_code = COALESCE($6, zip_code),
    state = COALESCE($7, state),
    gender = COALESCE($8, gender),
    marital_status = COALESCE($9, marital_status),
    phone1 = COALESCE($10, phone1),
    phone2 = COALESCE($11, phone2),
    occupation = COALESCE($12, occupation),
    img_url = COALESCE($13, img_url),
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, password, email_verified, role, verification_code, verification_code_expires_at, account_enabled, last_login, first_name, last_name, address, lga, zip_code, about_us, state, gender, marital_status, phone1, phone2, occupation, terms_accepted, img_url, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID            uuid.UUID      `db:"id" json:"id"`
	FirstName     sql.NullString `db:"first_name" json:"first_name"`
	LastName      sql.NullString `db:"last_name" json:"last_name"`
	Address       sql.NullString `db:"address" json:"address"`
	Lga           sql.NullString `db:"lga" json:"lga"`
	ZipCode       sql.NullString `db:"zip_code" json:"zip_code"`
	State         sql.NullString `db:"state" json:"state"`
	Gender        sql.NullString `db:"gender" json:"gender"`
	MaritalStatus sql.NullString `db:"marital_status" json:"marital_status"`
	Phone1        sql.NullString `db:"phone1" json:"phone1"`
	Phone2        sql.NullString `db:"phone2" json:"phone2"`
	Occupation    sql.NullString `db:"occupation" json:"occupation"`
	ImgUrl        sql.NullString `db:"img_url" json:"img_url"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfile,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Address,
		arg.Lga,
		arg.ZipCode,
		arg.State,
		arg.Gender,
		arg.MaritalStatus,
		arg.Phone1,
		arg.Phone2,
		arg.Occupation,
		arg.ImgUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.EmailVerified,
		&i.Role,
		&i.VerificationCode,
		&i.VerificationCodeExpiresAt,
		&i.AccountEnabled,
		&i.LastLogin,
		&i.FirstName,
		&i.LastName,
		&i.Address,
		&i.Lga,
		&i.ZipCode,
		&i.AboutUs,
		&i.State,
		&i.Gender,
		&i.MaritalStatus,
		&i.Phone1,
		&i.Phone2,
		&i.Occupation,
		&i.TermsAccepted,
		&i.ImgUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users
SET
    role = $2
WHERE id = $1
`

type UpdateUserRoleParams struct {
	ID   uuid.UUID `db:"id" json:"id"`
	Role UserRole  `db:"role" json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRole, arg.ID, arg.Role)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users
SET account_enabled = $2
WHERE id = $1
`

type UpdateUserStatusParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	AccountEnabled bool      `db:"account_enabled" json:"account_enabled"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatus, arg.ID, arg.AccountEnabled)
	return err
}

const updateUserStatusAndRole = `-- name: UpdateUserStatusAndRole :exec
UPDATE users
SET
    account_enabled = $2,
    role = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserStatusAndRoleParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	AccountEnabled bool      `db:"account_enabled" json:"account_enabled"`
	Role           UserRole  `db:"role" json:"role"`
}

func (q *Queries) UpdateUserStatusAndRole(ctx context.Context, arg UpdateUserStatusAndRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatusAndRole, arg.ID, arg.AccountEnabled, arg.Role)
	return err
}

const verifyUser = `-- name: VerifyUser :exec
UPDATE users
SET
    email_verified = true,
    account_enabled = true,
    verification_code = NULL,
    verification_code_expires_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) VerifyUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, verifyUser, id)
	return err
}
