// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type UserRole string

const (
	UserRoleUser       UserRole = "user"
	UserRoleStaff      UserRole = "staff"
	UserRoleSupervisor UserRole = "supervisor"
	UserRoleAdmin      UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Deposit struct {
	ID        uuid.UUID `db:"id" json:"id"`
	TxID      uuid.UUID `db:"tx_id" json:"tx_id"`
	Status    string    `db:"status" json:"status"`
	Type      string    `db:"type" json:"type"`
	Months    int32     `db:"months" json:"months"`
	Amount    string    `db:"amount" json:"amount"`
	Receipt   string    `db:"receipt" json:"receipt"`
	LoanID    uuid.UUID `db:"loan_id" json:"loan_id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	Email     string    `db:"email" json:"email"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type Loan struct {
	ID                 uuid.UUID      `db:"id" json:"id"`
	LoanType           string         `db:"loan_type" json:"loan_type"`
	PrincipalAmount    string         `db:"principal_amount" json:"principal_amount"`
	InterestRate       string         `db:"interest_rate" json:"interest_rate"`
	TermMonths         sql.NullInt32  `db:"term_months" json:"term_months"`
	MonthlyPayment     sql.NullString `db:"monthly_payment" json:"monthly_payment"`
	AdminFee           string         `db:"admin_fee" json:"admin_fee"`
	TotalInterest      sql.NullString `db:"total_interest" json:"total_interest"`
	TotalRepayment     sql.NullString `db:"total_repayment" json:"total_repayment"`
	TotalRepaid        string         `db:"total_repaid" json:"total_repaid"`
	TotalUnpaid        string         `db:"total_unpaid" json:"total_unpaid"`
	NumberOfRepayments int32          `db:"number_of_repayments" json:"number_of_repayments"`
	Status             string         `db:"status" json:"status"`
	DueDate            sql.NullTime   `db:"due_date" json:"due_date"`
	ApprovedDate       sql.NullTime   `db:"approved_date" json:"approved_date"`
	NextPaymentDate    sql.NullTime   `db:"next_payment_date" json:"next_payment_date"`
	Collateral         string         `db:"collateral" json:"collateral"`
	BorrowerName       string         `db:"borrower_name" json:"borrower_name"`
	Email              string         `db:"email" json:"email"`
	GuarantorName      sql.NullString `db:"guarantor_name" json:"guarantor_name"`
	GuarantorEmail     sql.NullString `db:"guarantor_email" json:"guarantor_email"`
	GuarantorPhone     sql.NullString `db:"guarantor_phone" json:"guarantor_phone"`
	GuarantorIppisNo   sql.NullString `db:"guarantor_ippis_no" json:"guarantor_ippis_no"`
	BankName           sql.NullString `db:"bank_name" json:"bank_name"`
	AccountNumber      sql.NullString `db:"account_number" json:"account_number"`
	AccountHolder      sql.NullString `db:"account_holder" json:"account_holder"`
	Bvn                sql.NullString `db:"bvn" json:"bvn"`
	Occupation         sql.NullString `db:"occupation" json:"occupation"`
	EmployerName       sql.NullString `db:"employer_name" json:"employer_name"`
	EmployerAddress    sql.NullString `db:"employer_address" json:"employer_address"`
	EmployerPhone      sql.NullString `db:"employer_phone" json:"employer_phone"`
	IppisNo            sql.NullString `db:"ippis_no" json:"ippis_no"`
	Statement          sql.NullString `db:"statement" json:"statement"`
	AdminFeeReceipt    sql.NullString `db:"admin_fee_receipt" json:"admin_fee_receipt"`
	CollateralDocument sql.NullString `db:"collateral_document" json:"collateral_document"`
	LoanInterest       sql.NullString `db:"loan_interest" json:"loan_interest"`
	UserID             uuid.UUID      `db:"user_id" json:"user_id"`
	LoanTypeID         uuid.UUID      `db:"loan_type_id" json:"loan_type_id"`
	CreatedAt          time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt          time.Time      `db:"updated_at" json:"updated_at"`
}

type LoanType struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	Rate      string    `db:"rate" json:"rate"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type Staff struct {
	ID             uuid.UUID    `db:"id" json:"id"`
	Email          string       `db:"email" json:"email"`
	PasswordHash   string       `db:"password_hash" json:"password_hash"`
	FullName       string       `db:"full_name" json:"full_name"`
	Role           NullUserRole `db:"role" json:"role"`
	AccountEnabled sql.NullBool `db:"account_enabled" json:"account_enabled"`
	LastLoginAt    sql.NullTime `db:"last_login_at" json:"last_login_at"`
	CreatedAt      sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt      sql.NullTime `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID                        uuid.UUID      `db:"id" json:"id"`
	Email                     string         `db:"email" json:"email"`
	Password                  string         `db:"password" json:"password"`
	EmailVerified             bool           `db:"email_verified" json:"email_verified"`
	Role                      UserRole       `db:"role" json:"role"`
	VerificationCode          sql.NullString `db:"verification_code" json:"verification_code"`
	VerificationCodeExpiresAt sql.NullTime   `db:"verification_code_expires_at" json:"verification_code_expires_at"`
	AccountEnabled            bool           `db:"account_enabled" json:"account_enabled"`
	LastLogin                 time.Time      `db:"last_login" json:"last_login"`
	FirstName                 string         `db:"first_name" json:"first_name"`
	LastName                  string         `db:"last_name" json:"last_name"`
	Address                   string         `db:"address" json:"address"`
	Lga                       string         `db:"lga" json:"lga"`
	ZipCode                   string         `db:"zip_code" json:"zip_code"`
	AboutUs                   string         `db:"about_us" json:"about_us"`
	State                     string         `db:"state" json:"state"`
	Gender                    string         `db:"gender" json:"gender"`
	MaritalStatus             string         `db:"marital_status" json:"marital_status"`
	Phone1                    string         `db:"phone1" json:"phone1"`
	Phone2                    string         `db:"phone2" json:"phone2"`
	Occupation                string         `db:"occupation" json:"occupation"`
	TermsAccepted             bool           `db:"terms_accepted" json:"terms_accepted"`
	ImgUrl                    string         `db:"img_url" json:"img_url"`
	CreatedAt                 time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt                 time.Time      `db:"updated_at" json:"updated_at"`
}
