// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ApproveLoan(ctx context.Context, id uuid.UUID) error
	CountDeposits(ctx context.Context) (int64, error)
	CountDepositsByUserID(ctx context.Context, userID uuid.UUID) (int64, error)
	CountLoans(ctx context.Context) (int64, error)
	CountLoansByUserID(ctx context.Context, userID uuid.UUID) (int64, error)
	CountPendingLoans(ctx context.Context) (int64, error)
	CountStaffs(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateDeposit(ctx context.Context, arg CreateDepositParams) (Deposit, error)
	CreateLoan(ctx context.Context, arg CreateLoanParams) (Loan, error)
	CreateLoanType(ctx context.Context, arg CreateLoanTypeParams) (LoanType, error)
	CreateStaff(ctx context.Context, arg CreateStaffParams) (CreateStaffRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DashboardStats(ctx context.Context) (DashboardStatsRow, error)
	DeleteLoanType(ctx context.Context, id uuid.UUID) error
	DeleteStaff(ctx context.Context, id uuid.UUID) error
	GetAllStaff(ctx context.Context, arg GetAllStaffParams) ([]GetAllStaffRow, error)
	GetDepositByID(ctx context.Context, id uuid.UUID) (Deposit, error)
	GetDeposits(ctx context.Context, arg GetDepositsParams) ([]Deposit, error)
	GetDepositsByUserID(ctx context.Context, arg GetDepositsByUserIDParams) ([]Deposit, error)
	GetLoanByID(ctx context.Context, id uuid.UUID) (Loan, error)
	GetLoanTypeByID(ctx context.Context, id uuid.UUID) (LoanType, error)
	GetLoanTypeByName(ctx context.Context, id uuid.UUID) (LoanType, error)
	GetLoans(ctx context.Context, arg GetLoansParams) ([]Loan, error)
	GetLoansByUserID(ctx context.Context, arg GetLoansByUserIDParams) ([]Loan, error)
	GetStaffByEmail(ctx context.Context, email string) (Staff, error)
	GetStaffByID(ctx context.Context, id uuid.UUID) (GetStaffByIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserForLogin(ctx context.Context, email string) (GetUserForLoginRow, error)
	GetUsers(ctx context.Context, arg GetUsersParams) ([]GetUsersRow, error)
	ListLoanTypes(ctx context.Context) ([]LoanType, error)
	UpdateLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateLastLoginStaff(ctx context.Context, id uuid.UUID) error
	UpdateLoanRepayment(ctx context.Context, arg UpdateLoanRepaymentParams) error
	UpdateLoanStatus(ctx context.Context, arg UpdateLoanStatusParams) error
	UpdateLoanType(ctx context.Context, arg UpdateLoanTypeParams) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateStaff(ctx context.Context, arg UpdateStaffParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
	UpdateUserStatusAndRole(ctx context.Context, arg UpdateUserStatusAndRoleParams) error
	VerifyUser(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
